### ISSUE TITLE
Can you add a "Style" option to settings?

### ISSUE THREAD

**Issue by DilemmaGX** [MrBeanCpp/CursorFinder#2]
Well it's a great app, but I used another cursor set, which may look awkward using the default pixelate ones. I'm suggesting you to add a "style" setting option, to upload user's own `.cur` or `.ico` cursor, or simply finding the current cursor and use this. This will make this app a very well developed project.

**Comment by MrBeanCpp** [comment]
Thank you for your great idea! I'll do it as soon as I have free time.

**Comment by MrBeanCpp** [comment]
Commited. see be18d24dfa951aa00131ad5167b0cbe1b0553728
Place you own cursor Image to the same directory of `.exe`， and rename it to `cursor`， like:
- `cursor.cur`
- `cursor.ico`
- ... `(.jpg jpeg png)`
