### ISSUE TITLE
新版本运行出现问题

### ISSUE THREAD

**Issue by austinzzzzzz** [MrBeanCpp/CursorFinder#4]
![image](https://github.com/user-attachments/assets/3da97e86-e4b8-424a-b576-7a0dd08f7cd5)

**Comment by MrBeanCpp** [comment]
应该是换了编译器忘记重新打包了 抱歉
已经更新了新的压缩包：[v1.2.0](https://github.com/MrBeanCpp/CursorFinder/releases/tag/v1.2.0)
