### ISSUE TITLE
当鼠标移动至扩展屏会导致变大不生效

### ISSUE THREAD

**Issue by LuisRain** [MrBeanCpp/CursorFinder#6]
环境：笔记本（主屏幕2k）+扩展屏（4k）；windows11，amd 7840h cpu
描述：在笔记本打开，鼠标晃动会变大。但是如果鼠标移动至扩展屏，左右晃动幅度大小均没有任何反应

**Comment by MrBeanCpp** [comment]
解决啦 可以试试新版
see [release v1.2.1](https://github.com/MrBeanCpp/CursorFinder/releases/tag/v1.2.1)

**Comment by LuisRain** [comment]
> 解决啦 可以试试新版 see [release v1.2.1](https://github.com/MrBeanCpp/CursorFinder/releases/tag/v1.2.1)

太酷了，感谢作者
